# Generated by Django 5.1.2 on 2024-11-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_carddb_prod_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddb',
            name='Prod_image',
        ),
        migrations.AddField(
            model_name='carddb',
            name='Prod_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart Images'),
        ),
    ]
